const first=(o,keys)=>{for(const k of keys){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return''};
const ACTIONS=[1,2,3,4,5,6].map(n=>({id:`damage_${n}x`,label:`${n}x o dano`,description:`Bola única do usuário com ${n}x de dano.`,params:[]}));
function eventOf(raw={}){return raw.event||raw.payload?.event||{}}
export function normalizeUser(raw={}){const e=eventOf(raw),u=typeof raw.user==='object'?raw.user:(raw.sender||raw.viewer||raw.author||{});const uniqueId=String(e.user||first(e,['uniqueId','username','userName'])||first(u,['uniqueId','unique_id','username','userName'])||first(raw,['uniqueId','username','userName'])||'').trim().replace(/^@/,'');const avatar=String(first(e,['profilePictureUrl','profilePicture','avatarUrl','avatar','image','photoUrl','userAvatar'])||first(u,['profilePictureUrl','profilePicture','avatarUrl','avatar','image','photoUrl','userAvatar'])||first(raw,['profilePictureUrl','profilePicture','avatarUrl','avatar','image','photoUrl','userAvatar'])||'');return{userId:String(first(e,['userId','user_id','id','uid'])||first(u,['userId','user_id','id','uid'])||first(raw,['userId','user_id'])||''),uniqueId,nickname:String(first(e,['nickname','displayName','name'])||first(u,['nickname','displayName','name'])||''),avatar}}
function clean(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8)}
function format(v){const c=clean(v);return c.length>4?c.slice(0,4)+'-'+c.slice(4):c}
export function liveBridge(game){let session=null,rules=[];const livePlayers=new Set();const manifest={protocol:'liveplus-game-manifest-v1',gameId:'mine',name:'Mine · Live Breaker',icon:'MB',version:'0.2.3',actions:ACTIONS};const $=s=>document.querySelector(s);
function status(text,kind=''){if($('#status'))$('#status').textContent=text;if($('#pairMessage'))$('#pairMessage').textContent=text;$('#statusDot')?.setAttribute('data-kind',kind)}
function renderRules(){const box=$('#ruleCards');if(!box)return;box.replaceChildren();for(const a of ACTIONS){const rule=rules.find(r=>String(r.actionId||r.action||r.command)==a.id);const el=document.createElement('div');el.className='rule-card'+(rule?' active':'');el.innerHTML=`<strong>${a.label}</strong><small>${rule?'ATIVO':'SEM REGRA'}</small>`;box.appendChild(el)}}
function execute(data={}){const action=String(data.action||data.command||data.actionId||''),m=action.match(/^damage_([1-6])x$/);if(!m)return false;const user=normalizeUser(data),key=(user.userId||user.uniqueId).toLowerCase();if(!key||user.uniqueId.toLowerCase()==='tiktok')return false;if(livePlayers.has(key))return true;const ok=game.command('spawn_ball',{user:{...user,power:Number(m[1])}});if(ok)livePlayers.add(key);return ok}
function resetPlayers(){livePlayers.clear();return true}
function setHud(v){$('#liveHud').hidden=!v;$('#liveHudToggle').checked=!!v;try{localStorage.setItem('mine-live-hud',v?'1':'0')}catch{}}
function resolve(raw){const text=String(raw||'').trim(),ticket=window.LivePlusGameSDK?.parseTicket?.(text)||null;if(ticket){window.LivePlusGameSDK?.configureRelay?.(ticket.endpoint);return{code:clean(ticket.code),value:text}}const code=clean(text);return{code,value:code}}
async function connect(raw){if(!window.LivePlusGameSDK?.Session){status('SDK LIVE+ não carregado','err');return false}const target=resolve(raw??$('#panelCode')?.value),code=target.code;if($('#panelCode'))$('#panelCode').value=format(code);if(code.length!==8){status('Código inválido','err');return false}try{session?.disconnect?.()}catch{}status('Conectando…','warn');session=new LivePlusGameSDK.Session({storageKey:'mine-liveplus-token',manifest});session.addEventListener('connected',()=>{status('Painel conectado','ok');try{localStorage.setItem('mine-panel-code',format(code))}catch{}setTimeout(()=>{$('#panelModal')?.classList.remove('show');game.setPaused?.(false)},250)});session.addEventListener('command',e=>execute(e.detail||{}));session.addEventListener('message',e=>{const d=e.detail||{};if(d.type==='rules_sync'&&Array.isArray(d.rules)){rules=d.rules;renderRules()}});session.addEventListener('lost',()=>status('Painel offline',''));session.addEventListener('rejected',e=>status(e.detail?.reason||'Sessão recusada','err'));try{await session.connect(target.value);return true}catch(e){status(e?.message||'Falha ao conectar','err');return false}}
function bind(){const modal=$('#panelModal'),input=$('#panelCode');$('#panelButton').onclick=()=>modal.classList.add('show');$('#closePanel').onclick=()=>modal.classList.remove('show');$('#connectPanel').onclick=()=>connect();if(input){window.LivePlusGameSDK?.installPasteBridge?.(input);try{input.value=localStorage.getItem('mine-panel-code')||''}catch{}input.oninput=e=>e.target.value=format(e.target.value);input.onkeydown=e=>{if(e.key==='Enter')connect()}}let hud=false;try{hud=localStorage.getItem('mine-live-hud')==='1'}catch{}setHud(hud);$('#liveHudToggle').onchange=e=>setHud(e.target.checked);renderRules()}
bind();window.MineLive={manifest,connect,execute,normalizeUser,resetPlayers,getRules:()=>rules.slice(),getSession:()=>session};return window.MineLive}