const first=(o,keys)=>{for(const k of keys){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return''};
const ACTIONS=[1,2,3,4,5,6].map(n=>({id:`damage_${n}x`,label:`${n}x o dano`,description:`Bola única do usuário com ${n}x de dano.`,params:[]}));
function eventOf(raw={}){return raw.event||raw.payload?.event||{}}
export function normalizeUser(raw={}){const e=eventOf(raw),u=typeof raw.user==='object'?raw.user:(raw.sender||raw.viewer||raw.author||{});const uniqueId=String(e.user||first(e,['uniqueId','username','userName'])||first(u,['uniqueId','unique_id','username','userName'])||first(raw,['uniqueId','username','userName'])||'').trim().replace(/^@/,'');const avatar=String(first(e,['avatar','avatarUrl','profilePictureUrl','profilePicture','image','photoUrl','userAvatar'])||first(u,['avatar','avatarUrl','profilePictureUrl','profilePicture','image','photoUrl','userAvatar'])||first(raw,['avatar','avatarUrl','profilePictureUrl','profilePicture','image','photoUrl','userAvatar'])||'');return{userId:String(first(e,['userId','user_id','id','uid'])||first(u,['userId','user_id','id','uid'])||first(raw,['userId','user_id'])||''),uniqueId,nickname:String(first(e,['nickname','displayName','name'])||first(u,['nickname','displayName','name'])||''),avatar}}
function clean(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8)}
function format(v){const c=clean(v);return c.length>4?c.slice(0,4)+'-'+c.slice(4):c}
function actionId(r={}){return String(first(r,['actionId','action','command'])||'')}
function giftName(r={}){const g=r.gift&&typeof r.gift==='object'?r.gift:{};return String(first(r,['giftName','triggerName'])||first(g,['name','giftName','title'])||(typeof r.gift==='string'?r.gift:'')||'Presente').slice(0,80)}
function giftIcon(r={}){const g=r.gift&&typeof r.gift==='object'?r.gift:{};return String(first(r,['giftIcon','giftImage','icon','image'])||first(g,['icon','image','iconUrl','imageUrl','pictureUrl'])||'')}
function giftValue(r={}){const g=r.gift&&typeof r.gift==='object'?r.gift:{};return Number(first(r,['diamondCount','giftValue','value','diamonds','coins','coinValue'])||first(g,['diamondCount','value','diamonds','coins'])||0)}
function safeImageUrl(raw){try{const u=new URL(String(raw||''),location.href);return['https:','http:'].includes(u.protocol)&&u.href.length<2048?u.href:''}catch{return''}}
export function liveBridge(game){let session=null,rules=[],flashTimer=0,flashBusy=false;const flashQueue=[],livePlayers=new Set();const manifest={protocol:'liveplus-game-manifest-v1',gameId:'mine',name:'Mine · Live Breaker',icon:'MB',version:'0.3.3',actions:ACTIONS};const $=s=>document.querySelector(s);
function status(text,kind=''){if($('#status'))$('#status').textContent=text;if($('#pairMessage'))$('#pairMessage').textContent=text;$('#statusDot')?.setAttribute('data-kind',kind)}
function ruleCard(action,rule){const el=document.createElement('div');el.className='rule-card'+(rule?' active':' empty');const gift=document.createElement('div');gift.className='rule-gift';if(rule){const src=safeImageUrl(giftIcon(rule));if(src){const im=document.createElement('img');im.src=src;im.alt='';im.referrerPolicy='no-referrer';gift.appendChild(im)}else{const fallback=document.createElement('span');fallback.textContent='🎁';gift.appendChild(fallback)}}else{const fallback=document.createElement('span');fallback.textContent='—';gift.appendChild(fallback)}const copy=document.createElement('div');copy.className='rule-copy';const b=document.createElement('b');b.textContent=rule?giftName(rule):action.label;const small=document.createElement('small');small.textContent=rule?action.label:'SEM REGRA';copy.append(b,small);el.append(gift,copy);return el}
function renderRules(){const box=$('#ruleCards');if(!box)return;const map=new Map();for(const r of rules){const id=actionId(r);if(ACTIONS.some(a=>a.id===id)&&!map.has(id))map.set(id,r)}const ordered=[...ACTIONS].sort((a,b)=>{const ra=map.get(a.id),rb=map.get(b.id);if(ra&&!rb)return-1;if(!ra&&rb)return 1;if(ra&&rb)return giftValue(ra)-giftValue(rb);return ACTIONS.indexOf(a)-ACTIONS.indexOf(b)});box.replaceChildren();for(const a of ordered)box.appendChild(ruleCard(a,map.get(a.id)))}
function eventGift(data,rule){const e=eventOf(data),obj=e.gift&&typeof e.gift==='object'?e.gift:{};return{name:String(first(e,['giftName'])||(typeof e.gift==='string'?e.gift:'')||first(data,['giftName'])||first(obj,['name','giftName','title'])||(rule?giftName(rule):'Presente')),icon:safeImageUrl(first(e,['icon','giftIcon','giftImage'])||first(data,['icon','giftIcon','giftImage'])||first(obj,['icon','image','iconUrl','imageUrl','pictureUrl'])||(rule?giftIcon(rule):''))}}
function paintFlash(item){const box=$('#liveEventFlash');if(!box)return;box.replaceChildren();box.dataset.kind=item.kind;const avatar=document.createElement('div');avatar.className='live-event-avatar';if(item.user.avatar){const im=document.createElement('img');im.src=safeImageUrl(item.user.avatar);im.alt='';im.referrerPolicy='no-referrer';avatar.appendChild(im)}else avatar.textContent=(item.user.uniqueId[0]||'?').toUpperCase();const copy=document.createElement('div');copy.className='live-event-copy';const who=document.createElement('strong');who.textContent='@'+item.user.uniqueId;const text=document.createElement('span');text.textContent=item.kind==='follow'?'começou a seguir':`enviou ${item.name}`;copy.append(who,text);box.append(avatar,copy);if(item.kind==='gift'){const gift=document.createElement('div');gift.className='live-event-gift';if(item.icon){const gi=document.createElement('img');gi.src=item.icon;gi.alt='';gi.referrerPolicy='no-referrer';gift.appendChild(gi)}else gift.textContent='🎁';const effect=document.createElement('b');effect.className='live-event-effect';effect.textContent=item.power+'x';box.append(gift,effect)}else{const mark=document.createElement('div');mark.className='live-event-follow';mark.textContent='＋';box.append(mark)}box.classList.remove('show');void box.offsetWidth;box.classList.add('show')}
function runFlashQueue(){if(flashBusy||!flashQueue.length)return;flashBusy=true;const item=flashQueue.shift();paintFlash(item);clearTimeout(flashTimer);flashTimer=setTimeout(()=>{const box=$('#liveEventFlash');box?.classList.remove('show');setTimeout(()=>{flashBusy=false;runFlashQueue()},170)},1650)}
function queueFlash(item){if(!item?.user?.uniqueId)return;if(flashQueue.length>=5)flashQueue.shift();flashQueue.push(item);runFlashQueue()}
function flashEvent(data,action,power,user){const e=eventOf(data),type=String(e.type||data.eventType||'').toLowerCase(),rule=rules.find(r=>actionId(r)===action);if(type==='follow'){queueFlash({kind:'follow',user});return}const gift=eventGift(data,rule);queueFlash({kind:'gift',user,name:gift.name,icon:gift.icon,power})}
function execute(data={}){const action=String(data.action||data.command||data.actionId||''),m=action.match(/^damage_([1-6])x$/);if(!m)return false;const user=normalizeUser(data),key=(user.userId||user.uniqueId).toLowerCase(),power=Number(m[1]);if(!key||user.uniqueId.toLowerCase()==='tiktok')return false;flashEvent(data,action,power,user);if(livePlayers.has(key)){game.command('boost_ball',{user:{...user,power}});return true}const ok=game.command('spawn_ball',{user:{...user,power}});if(ok)livePlayers.add(key);return ok}
function resetPlayers(){livePlayers.clear();flashQueue.length=0;flashBusy=false;clearTimeout(flashTimer);$('#liveEventFlash')?.classList.remove('show');return true}
function setHud(v){$('#liveHud').hidden=!v;$('#liveHudToggle').checked=!!v;try{localStorage.setItem('mine-live-hud',v?'1':'0')}catch{}}
function resolve(raw){const text=String(raw||'').trim(),ticket=window.LivePlusGameSDK?.parseTicket?.(text)||null;if(ticket){window.LivePlusGameSDK?.configureRelay?.(ticket.endpoint);return{code:clean(ticket.code),value:text}}const code=clean(text);return{code,value:code}}
async function connect(raw){if(!window.LivePlusGameSDK?.Session){status('SDK LIVE+ não carregado','err');return false}const target=resolve(raw??$('#panelCode')?.value),code=target.code;if($('#panelCode'))$('#panelCode').value=format(code);if(code.length!==8){status('Código inválido','err');return false}try{session?.disconnect?.()}catch{}status('Conectando…','warn');session=new LivePlusGameSDK.Session({storageKey:'mine-liveplus-token',manifest});session.addEventListener('connected',()=>{status('Painel conectado','ok');try{localStorage.setItem('mine-panel-code',format(code))}catch{}setTimeout(()=>{$('#panelModal')?.classList.remove('show');game.setPaused?.(false)},250)});session.addEventListener('command',e=>execute(e.detail||{}));session.addEventListener('message',e=>{const d=e.detail||{};if(d.type==='rules_sync'&&Array.isArray(d.rules)){rules=d.rules;renderRules()}});session.addEventListener('lost',()=>status('Painel offline',''));session.addEventListener('rejected',e=>status(e.detail?.reason||'Sessão recusada','err'));try{await session.connect(target.value);return true}catch(e){status(e?.message||'Falha ao conectar','err');return false}}
function bind(){const modal=$('#panelModal'),input=$('#panelCode');$('#panelButton').onclick=()=>modal.classList.add('show');$('#closePanel').onclick=()=>modal.classList.remove('show');$('#connectPanel').onclick=()=>connect();if(input){window.LivePlusGameSDK?.installPasteBridge?.(input);try{input.value=localStorage.getItem('mine-panel-code')||''}catch{}input.oninput=e=>e.target.value=format(e.target.value);input.onkeydown=e=>{if(e.key==='Enter')connect()}}let hud=false;try{hud=localStorage.getItem('mine-live-hud')==='1'}catch{}setHud(hud);$('#liveHudToggle').onchange=e=>setHud(e.target.checked);renderRules()}
bind();window.MineLive={manifest,connect,execute,normalizeUser,resetPlayers,getRules:()=>rules.slice(),getSession:()=>session};return window.MineLive}